use std::path::Path;

use crate::config::print_autogen_notice;
mod config;
mod steam;
mod files;

fn main() {
    config::create_default_config_if_not_exists();

    if config::is_autogenerated() {
        print_autogen_notice();
    }

    files::create_storage_if_not_exists();
    let steam_path : String = config::read_config_path("STEAM_PATH");
    if steam_path == "" || !Path::new(&steam_path).exists() {
        eprintln!("Error: STEAM_PATH is invalid or $HOME could not be resolved, exiting.");
        return;
    }
    let steam_apps: Vec<steam::SteamApp> = steam::get_all_steam_apps(&steam_path);
    for app in steam_apps.iter() {
        println!("--- App: {} || {} ---", app.app_id, app.name);
        if steam::desktop_file_is_in_storage(&app.app_id) { 
            println!("Desktop file already exists, skipping...");
            continue; 
        }
        let app_icon_path: String;
        if files::get_icon_in_storage(&app.app_id).is_none() {
            println!("Copying app icon to storage...");
            let cached_app_icon_path: String;
            match steam::get_icon_path(&steam_path, app.app_id) {
                Some(path) => { cached_app_icon_path = path; }
                None => { 
                    eprintln!("Error getting icon path for App ID: {}", app.app_id);
                    continue;
                }
            }
            if !files::copy_img_to_storage(&cached_app_icon_path, &app.app_id) {
                eprintln!("Error copying icon to storage for App ID: {}", app.app_id);
                continue;
            }
        }
        app_icon_path = files::get_icon_in_storage(&app.app_id).unwrap();
        if !steam::create_desktop_file(&app.app_id, &app.name, &app_icon_path){
            eprintln!("Error creating desktop file for App {}", app.app_id);
        }
    }
    println!("Checking for broken desktop files...");
    steam::check_for_broken_dekstop_files(steam_apps);
    return;
}